export const CONSTANTS = {
  BASE_URL: "https://opentdb.com",
  MOVIE_CATEGORY_CODE: "11",
  TV_CATEGORY_CODE: "14",
  SUCCESS_RESPONSE_CODE: 0,
  MIN_QUESTIONS_REQUEST: 1,
  MAX_QUESTIONS_REQUEST: 50,
  ENDPOINT: "api.php",
};
