export const tvShowCast = {
  adult: false,
  backdrop_path: "/xCdCsHCH7VCQqaDUPD5tG6omMsB.jpg",
  genre_ids: [10767, 35],
  id: 1489,
  origin_country: ["US"],
  original_language: "en",
  original_name: "Jimmy Kimmel Live!",
  overview:
    "Jimmy Kimmel Live! is an American late-night talk show, created and hosted by Jimmy Kimmel and broadcast on ABC.",
  popularity: 83.171,
  poster_path: "/hWLCBGQ2RFpjXyaKRMbL5bGEEDT.jpg",
  first_air_date: "2003-01-26",
  name: "Jimmy Kimmel Live!",
  vote_average: 5.6,
  vote_count: 127,
  character: "character",
  credit_id: "525708b3760ee3776a047e92",
  episode_count: 1,
  media_type: "tv",
};

export const movieCast = {
  adult: false,
  backdrop_path: "backdrop_path",
  genre_ids: [18, 12],
  id: 300450,
  original_language: "en",
  original_title: "Flying Horse",
  overview:
    "A biopic of pioneer photographer Eadweard Muybridge, following the courtship and love affair between Muybridge's wife, Flora, and Harry Larkyns.",
  popularity: 1.973,
  poster_path: "poster_path",
  release_date: "release_date",
  title: "Flying Horse",
  video: false,
  vote_average: 0.0,
  vote_count: 0,
  credit_id: "5518744f9251412cb9003007",
  department: "Writing",
  character: "character",
  job: "Writer",
  media_type: "movie",
};

export const moviesGenres = {
  genres: [
    {
      id: 28,
      name: "Ação",
    },
    {
      id: 12,
      name: "Aventura",
    },
    {
      id: 16,
      name: "Animação",
    },
    {
      id: 35,
      name: "Comédia",
    },
    {
      id: 80,
      name: "Crime",
    },
    {
      id: 99,
      name: "Documentário",
    },
    {
      id: 18,
      name: "Drama",
    },
    {
      id: 10751,
      name: "Família",
    },
    {
      id: 14,
      name: "Fantasia",
    },
    {
      id: 36,
      name: "História",
    },
    {
      id: 27,
      name: "Terror",
    },
    {
      id: 10402,
      name: "Música",
    },
    {
      id: 9648,
      name: "Mistério",
    },
    {
      id: 10749,
      name: "Romance",
    },
    {
      id: 878,
      name: "Ficção científica",
    },
    {
      id: 10770,
      name: "Cinema TV",
    },
    {
      id: 53,
      name: "Thriller",
    },
    {
      id: 10752,
      name: "Guerra",
    },
    {
      id: 37,
      name: "Faroeste",
    },
  ],
};

export const tvShowGenres = {
  genres: [
    {
      id: 10759,
      name: "Action & Adventure",
    },
    {
      id: 16,
      name: "Animação",
    },
    {
      id: 35,
      name: "Comédia",
    },
    {
      id: 80,
      name: "Crime",
    },
    {
      id: 99,
      name: "Documentário",
    },
    {
      id: 18,
      name: "Drama",
    },
    {
      id: 10751,
      name: "Família",
    },
    {
      id: 10762,
      name: "Kids",
    },
    {
      id: 9648,
      name: "Mistério",
    },
    {
      id: 10763,
      name: "News",
    },
    {
      id: 10764,
      name: "Reality",
    },
    {
      id: 10765,
      name: "Sci-Fi & Fantasy",
    },
    {
      id: 10766,
      name: "Soap",
    },
    {
      id: 10767,
      name: "Talk",
    },
    {
      id: 10768,
      name: "War & Politics",
    },
    {
      id: 37,
      name: "Faroeste",
    },
  ],
};

export const famous = {
  adult: false,
  also_known_as: [
    "Gary Leonard Oldman",
    "แกรี โอลด์แมน",
    "Гари Олдман",
    "ゲイリー・オールドマン",
    "غاري أولدمان",
    "게리 올드먼",
    "게리 올드만",
    "Γκάρι Όλντμαν",
    "Гэри Олдман",
    "Ґері Олдмен",
    "Гері Олдмен",
    "گری اولدمن",
    "გარი ოლდმენი",
    "加里·奥德曼",
  ],
  biography:
    "Gary Leonard Oldman (born 21 March 1958) is an English actor and filmmaker. Regarded as one of the best actors of his generation, he is known for his versatility and intense acting style. He received various accolades, including an Academy Award, a Golden Globe Award, a Screen Actors Guild Award, and three British Academy Film Awards. His films have grossed over $11 billion worldwide, making him one of the highest-grossing actors to date.\n\nOldman began acting in theatre in 1979 and made his film debut in Remembrance (1982). He continued to follow a stage career in London's Royal Court and was a member of the Royal Shakespeare Company, with credits including Cabaret, Romeo and Juliet, Entertaining Mr Sloane, Saved, The Country Wife and Hamlet. He rose to prominence in British film with his portrayals of Sid Vicious in Sid and Nancy (1986), Joe Orton in Prick Up Your Ears (1987) and Rosencrantz in Rosencrantz & Guildenstern Are Dead (1990), while also attracting attention as the leader of a gang of football hooligans in the television film The Firm (1989). Regarded as a member of the \"Brit Pack\", he achieved greater recognition as a New York gangster in State of Grace (1990), Lee Harvey Oswald in JFK (1991) and Count Dracula in Bram Stoker's Dracula (1992).\n\nOldman portrayed the villains in films such as True Romance (1993), The Fifth Element (1997), Air Force One (1997) and The Contender (2000); corrupt DEA agent Norman Stansfield, whom he played in Léon: The Professional (1994), was called one of cinema's best villains. He also played Ludwig van Beethoven in Immortal Beloved (1994) and later appeared in franchise roles such as Sirius Black in the Harry Potter series, James Gordon in The Dark Knight Trilogy (2005–2012) and a human leader, Dreyfus in Dawn of the Planet of the Apes (2014). He won the Academy Award for Best Actor for his role as Winston Churchill in Darkest Hour (2017), and was nominated for his portrayals of George Smiley in Tinker Tailor Soldier Spy (2011) and Herman J. Mankiewicz in Mank (2020).\n\nOldman was executive producer of films like The Contender, Plunkett & Macleane (1999) and Nil by Mouth (1997), the latter of which he also wrote and directed. He featured in television shows such as Fallen Angels, Tracey Takes On... and Friends, voiced Ignitius and Viktor Reznov respectively in The Legend of Spyro and Call of Duty video games and appeared in music videos for David Bowie, Guns N' Roses and Annie Lennox.",
  birthday: "1958-03-21",
  deathday: "deathday",
  gender: 2,
  homepage: "homepage",
  id: 64,
  imdb_id: "nm0000198",
  known_for_department: "Acting",
  name: "Gary Oldman",
  place_of_birth: "New Cross, London, England, UK",
  popularity: 185.954,
  profile_path: "/yhaSM5habNNI1Tf4ALRwRk3VvSZ.jpg",
  images: {
    profiles: [
      {
        aspect_ratio: 0.667,
        height: 2160,
        iso_639_1: "iso_639_1",
        file_path: "/yhaSM5habNNI1Tf4ALRwRk3VvSZ.jpg",
        vote_average: 5.33,
        vote_count: 9,
        width: 1440,
      },
      {
        aspect_ratio: 0.667,
        height: 622,
        iso_639_1: "iso_639_1",
        file_path: "/hHP0769L7YrApkMKCOyb9cwgxBW.jpg",
        vote_average: 5.252,
        vote_count: 4,
        width: 415,
      },
      {
        aspect_ratio: 0.667,
        height: 984,
        iso_639_1: "iso_639_1",
        file_path: "/2v9FVVBUrrkW2m3QOcYkuhq9A6o.jpg",
        vote_average: 5.22,
        vote_count: 13,
        width: 656,
      },
      {
        aspect_ratio: 0.666,
        height: 2048,
        iso_639_1: "iso_639_1",
        file_path: "/4HxoaJ8619S6eHOO901FMuxQ1FE.jpg",
        vote_average: 5.19,
        vote_count: 5,
        width: 1363,
      },
      {
        aspect_ratio: 0.667,
        height: 2259,
        iso_639_1: "iso_639_1",
        file_path: "/7DKdzGtFDbE84Pf96IQ2HDDilCd.jpg",
        vote_average: 5.106,
        vote_count: 2,
        width: 1506,
      },
      {
        aspect_ratio: 0.667,
        height: 1024,
        iso_639_1: "iso_639_1",
        file_path: "/3mr77nrZ1sUFBZrhuNyIQG4giYf.jpg",
        vote_average: 5.106,
        vote_count: 2,
        width: 683,
      },
      {
        aspect_ratio: 0.666,
        height: 1000,
        iso_639_1: "iso_639_1",
        file_path: "/pp21unPsFDSE3uGs5x9J65AaqMn.jpg",
        vote_average: 5.106,
        vote_count: 2,
        width: 666,
      },
      {
        aspect_ratio: 0.667,
        height: 949,
        iso_639_1: "iso_639_1",
        file_path: "/peKJ7hFHE0Z7YaO9dUmCChI2iHA.jpg",
        vote_average: 5.106,
        vote_count: 2,
        width: 633,
      },
      {
        aspect_ratio: 0.666,
        height: 650,
        iso_639_1: "iso_639_1",
        file_path: "/3cOTcPeJNxBjHashuZ1KFAiU2T8.jpg",
        vote_average: 5.106,
        vote_count: 2,
        width: 433,
      },
      {
        aspect_ratio: 0.667,
        height: 600,
        iso_639_1: "iso_639_1",
        file_path: "/y2M4UjTopWDu3uVkQDy6pzUYUGd.jpg",
        vote_average: 5.106,
        vote_count: 2,
        width: 400,
      },
      {
        aspect_ratio: 0.667,
        height: 1080,
        iso_639_1: "iso_639_1",
        file_path: "/g1ueDq0Px0sa8CmOk0dZwocpwLb.jpg",
        vote_average: 5.106,
        vote_count: 2,
        width: 720,
      },
      {
        aspect_ratio: 0.667,
        height: 835,
        iso_639_1: "iso_639_1",
        file_path: "/j5eCpaDiZaROR2d73gQmhc4rz5s.jpg",
        vote_average: 5.106,
        vote_count: 2,
        width: 557,
      },
      {
        aspect_ratio: 0.667,
        height: 1080,
        iso_639_1: "iso_639_1",
        file_path: "/ioVNfh5m8IyoM1DXRIiOU658RXm.jpg",
        vote_average: 5.068,
        vote_count: 7,
        width: 720,
      },
    ],
  },
};

export const searchFamousResult = [
  {
    adult: false,
    gender: 2,
    id: 52583,
    known_for_department: "Acting",
    name: "Wagner Moura",
    original_name: "Wagner Moura",
    popularity: 26.295,
    profile_path: "/yJjV1ZCQbCSSgRy05FncCKjyaY4.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/go5LNIFH9IdoSwv8j9cNyTk2uPU.jpg",
        id: 63351,
        name: "Narcos",
        original_language: "en",
        original_name: "Narcos",
        overview:
          "A gritty chronicle of the war against Colombia's infamously violent and powerful drug cartels.",
        poster_path: "/rTmal9fDbwh5F0waol2hq35U4ah.jpg",
        media_type: "tv",
        genre_ids: [80, 18],
        popularity: 86.0,
        first_air_date: "2015-08-28",
        vote_average: 8.005,
        vote_count: 2490,
        origin_country: ["US"],
      },
      {
        adult: false,
        backdrop_path: "/tGb044NgQYQJr58fta5O3OB6SpQ.jpg",
        id: 7347,
        title: "Elite Squad",
        original_language: "pt",
        original_title: "Tropa de Elite",
        overview:
          "In 1997, before the visit of the pope to Rio de Janeiro, Captain Nascimento from BOPE (Special Police Operations Battalion) is assigned to eliminate the risks of the drug dealers in a dangerous slum nearby where the pope intends to be lodged.",
        poster_path: "/lwIXz785N2fXi8hsBr1IXciFlkM.jpg",
        media_type: "movie",
        genre_ids: [18, 28, 80],
        popularity: 31.549,
        release_date: "2007-10-12",
        video: false,
        vote_average: 8.057,
        vote_count: 2149,
      },
    ],
  },
];

export const trendingFamous = {
  page: 1,
  results: [
    {
      adult: false,
      gender: 2,
      id: 64,
      known_for: [
        {
          adult: false,
          backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
          genre_ids: [18, 28, 80, 53],
          id: 155,
          media_type: "movie",
          original_language: "en",
          original_title: "The Dark Knight",
          overview:
            "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
          poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
          release_date: "2008-07-16",
          title: "The Dark Knight",
          video: false,
          vote_average: 8.5,
          vote_count: 30631,
        },
        {
          backdrop_path: "/aRKQdF6AGbhnF9IAyJbte5epH5R.jpg",
          first_air_date: "2023-08-31",
          genre_ids: [10759, 10765],
          id: 111110,
          media_type: "tv",
          name: "ONE PIECE",
          origin_country: ["US"],
          original_language: "en",
          original_name: "ONE PIECE",
          overview:
            "With his straw hat and ragtag crew, young pirate Monkey D. Luffy goes on an epic voyage for treasure in this live-action adaptation of the popular manga.",
          poster_path: "/rVX05xRKS5JhEYQFObCi4lAnZT4.jpg",
          vote_average: 8.2,
          vote_count: 646,
        },
      ],
      known_for_department: "Acting",
      name: "Gary Oldman",
      popularity: 250.277,
      profile_path: "/yhaSM5habNNI1Tf4ALRwRk3VvSZ.jpg",
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

export const tvShow = {
  adult: false,
  backdrop_path: "/aRKQdF6AGbhnF9IAyJbte5epH5R.jpg",
  created_by: [
    {
      id: 1225826,
      credit_id: "64f08253caa50800e951a4f1",
      name: "Steven Maeda",
      gender: 2,
      profile_path: "/4QwZvyeiOOsIy3jhtLgS5iy7Whw.jpg",
    },
    {
      id: 1562489,
      credit_id: "64f0824de0ca7f00ae390791",
      name: "Matt Owens",
      gender: 2,
      profile_path: "/9557f2EgDxHEhnXmXf6Hx9io76S.jpg",
    },
  ],
  episode_run_time: [],
  first_air_date: "2023-08-31",
  genres: [
    {
      id: 10759,
      name: "Action & Adventure",
    },
    {
      id: 10765,
      name: "Sci-Fi & Fantasy",
    },
  ],
  homepage: "https://www.netflix.com/title/80217863",
  id: 111110,
  in_production: true,
  languages: ["en"],
  last_air_date: "2023-08-31",
  last_episode_to_air: {
    id: 4557395,
    name: "O mais procurado do East Blue",
    overview:
      "A tripulação dos chapéus de palha luta para derrotar Arlong e os homens-peixe de uma vez por todas. Após uma difícil reunião de família, Luffy fica mais perto do seu sonho.",
    vote_average: 7.839,
    vote_count: 31,
    air_date: "2023-08-31",
    episode_number: 8,
    episode_type: "finale",
    production_code: "",
    runtime: 49,
    season_number: 1,
    show_id: 111110,
    still_path: "/nMiFAm30mAkNQS7YGrMEdMCT4NJ.jpg",
  },
  name: "ONE PIECE: A Série",
  next_episode_to_air: "next_episode_to_air",
  networks: [
    {
      id: 213,
      logo_path: "/wwemzKWzjKYJFfCeiB57q3r4Bcm.png",
      name: "Netflix",
      origin_country: "",
    },
  ],
  number_of_episodes: 8,
  number_of_seasons: 1,
  origin_country: ["US"],
  original_language: "en",
  original_name: "ONE PIECE",
  overview:
    "O jovem pirata Monkey D. Luffy veste o chapéu de palha e, com sua tripulação atrapalhada, zarpa em uma jornada épica nesta adaptação em live-action do popular mangá.",
  popularity: 452.425,
  poster_path: "/y0VSmak9mSobl9QTKCvR7w4w6Ui.jpg",
  production_companies: [
    {
      id: 104720,
      logo_path: "logo_path",
      name: "Tomorrow Studios",
      origin_country: "US",
    },
    {
      id: 207514,
      logo_path: "logo_path",
      name: "Kaji Productions",
      origin_country: "US",
    },
    {
      id: 773,
      logo_path: "/qkcN6yZEyBw3cgO5DJu55LGEsf7.png",
      name: "Film Afrika",
      origin_country: "ZA",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "ZA",
      name: "South Africa",
    },
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  seasons: [
    {
      air_date: "2023-08-31",
      episode_count: 8,
      id: 164867,
      name: "Temporada 1",
      overview: "",
      poster_path: "/aesLt9fsKSA6KCgGxA60VVxjtLk.jpg",
      season_number: 1,
      vote_average: 8.1,
    },
  ],
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Returning Series",
  tagline: "Os piratas estão chegando.",
  type: "Scripted",
  vote_average: 8.247,
  vote_count: 651,
};
