import { QueryTvShowSeasonArgs } from "@generated-types";

export const handler = {
  handle: async (params: QueryTvShowSeasonArgs) => ({
    _id: "5f7b55393e2ec80037d661c7",
    air_date: "2023-08-31",
    episodes: [
      {
        air_date: "2023-08-31",
        episode_number: 1,
        episode_type: "standard",
        id: 2454621,
        name: "O amanhecer de uma aventura",
        overview:
          "Preso em um barco afundando, Luffy começa a jornada em busca do tesouro perdido do rei dos piratas. Só que, para isso, ele precisa de uma tripulação, um navio e um mapa.",
        production_code: "",
        runtime: 64,
        season_number: 1,
        show_id: 111110,
        still_path: "/uQsp24EqNOx3Xuhcru0zHGC25gF.jpg",
        vote_average: 8.267,
        vote_count: 176,
        crew: [
          {
            job: "Teleplay",
            department: "Writing",
            credit_id: "61349861b84f940062c5eb65",
            adult: false,
            gender: 2,
            id: 1225826,
            known_for_department: "Writing",
            name: "Steven Maeda",
            original_name: "Steven Maeda",
            popularity: 2.545,
            profile_path: "/4QwZvyeiOOsIy3jhtLgS5iy7Whw.jpg",
          },
          {
            job: "Teleplay",
            department: "Writing",
            credit_id: "613499eb2cde980062d51690",
            adult: false,
            gender: 2,
            id: 1562489,
            known_for_department: "Writing",
            name: "Matt Owens",
            original_name: "Matt Owens",
            popularity: 2.65,
            profile_path: "/9557f2EgDxHEhnXmXf6Hx9io76S.jpg",
          },
          {
            job: "Director of Photography",
            department: "Camera",
            credit_id: "64de2289b77d4b11425f1108",
            adult: false,
            gender: 1,
            id: 225120,
            known_for_department: "Camera",
            name: "Nicole Hirsch Whitaker",
            original_name: "Nicole Hirsch Whitaker",
            popularity: 0.884,
            profile_path: null,
          },
          {
            job: "Director",
            department: "Directing",
            credit_id: "64de23a437109700ac442bd0",
            adult: false,
            gender: 2,
            id: 1515079,
            known_for_department: "Directing",
            name: "Marc Jobst",
            original_name: "Marc Jobst",
            popularity: 4.15,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04ce8dbbb42013a22a666",
            adult: false,
            gender: 2,
            id: 37003,
            known_for_department: "Editing",
            name: "Kevin D. Ross",
            original_name: "Kevin D. Ross",
            popularity: 2.744,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04cfcebb99d01008b13d5",
            adult: false,
            gender: 1,
            id: 1410314,
            known_for_department: "Editing",
            name: "Tessa Verfuss",
            original_name: "Tessa Verfuss",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04d3a97a4e600ac3e3590",
            adult: false,
            gender: 0,
            id: 3946733,
            known_for_department: "Editing",
            name: "Eric Litman",
            original_name: "Eric Litman",
            popularity: 0.6,
            profile_path: null,
          },
        ],
        guest_stars: [
          {
            character: "Narrator (voice)",
            credit_id: "64f043fbdbbb4200c4e9f7a0",
            order: 500,
            adult: false,
            gender: 2,
            id: 6972,
            known_for_department: "Acting",
            name: "Ian McShane",
            original_name: "Ian McShane",
            popularity: 96.156,
            profile_path: "/q9qKbux5Jo76Sj8g3luxBt6rYtz.jpg",
          },
          {
            character: "Yasopp the Great",
            credit_id: "64f052a13a993700e2f78f92",
            order: 502,
            adult: false,
            gender: 0,
            id: 1184468,
            known_for_department: "Acting",
            name: "Stevel Marc",
            original_name: "Stevel Marc",
            popularity: 5.543,
            profile_path: "/n7NzuHjveJqZoEM5HFmblMGKdGp.jpg",
          },
          {
            character: "Lucky Roux",
            credit_id: "64f052c197a4e600fea874f1",
            order: 503,
            adult: false,
            gender: 2,
            id: 2340022,
            known_for_department: "Acting",
            name: "Ntlanhla Morgan Kutu",
            original_name: "Ntlanhla Morgan Kutu",
            popularity: 0.652,
            profile_path: "/c4wO2qJkVE24Wdc1Okz8zEB7gW6.jpg",
          },
          {
            character: "Gold Roger",
            credit_id: "64f0b37febb99d013bced2ab",
            order: 504,
            adult: false,
            gender: 2,
            id: 76068,
            known_for_department: "Acting",
            name: "Michael Dorman",
            original_name: "Michael Dorman",
            popularity: 18.948,
            profile_path: "/624CKam4fVBcHATuOfsOEvPzCCh.jpg",
          },
          {
            character: "Captain Alvida",
            credit_id: "64f0b3accaa50800e951b80a",
            order: 505,
            adult: false,
            gender: 1,
            id: 3209866,
            known_for_department: "Acting",
            name: "Ilia Isorelýs Paulino",
            original_name: "Ilia Isorelýs Paulino",
            popularity: 3.92,
            profile_path: "/n2TH0b4oCk1Dsc33rrfjdfPgK9e.jpg",
          },
          {
            character: "Young Luffy",
            credit_id: "64f0b3c1ebb99d00e3e7ab02",
            order: 506,
            adult: false,
            gender: 2,
            id: 2188198,
            known_for_department: "Acting",
            name: "Colton Osorio",
            original_name: "Colton Osorio",
            popularity: 24.608,
            profile_path: "/26QYXUN5sa6ZjFCy24y3nnL89SV.jpg",
          },
          {
            character: "Axe-Hand Morgan",
            credit_id: "64f0b3d7e0ca7f014f6a457b",
            order: 507,
            adult: false,
            gender: 2,
            id: 37093,
            known_for_department: "Acting",
            name: "Langley Kirkwood",
            original_name: "Langley Kirkwood",
            popularity: 8.414,
            profile_path: "/mtorXdi3X3v1V0KrrkUVfUAVQlX.jpg",
          },
          {
            character: "Higuma",
            credit_id: "64f0b3f877d23b0150390eff",
            order: 508,
            adult: false,
            gender: 2,
            id: 1838215,
            known_for_department: "Acting",
            name: "Tamer Burjaq",
            original_name: "Tamer Burjaq",
            popularity: 4.967,
            profile_path: "/rz1FOttxvkeVkAh7XxjBwd8eGgC.jpg",
          },
          {
            character: "Makino",
            credit_id: "64f0b40de0ca7f00ec86d76f",
            order: 509,
            adult: false,
            gender: 0,
            id: 4046635,
            known_for_department: "Acting",
            name: "Kathleen Stephens",
            original_name: "Kathleen Stephens",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Bogard",
            credit_id: "64f0b41d3a9937011cbdc02d",
            order: 510,
            adult: false,
            gender: 2,
            id: 1478709,
            known_for_department: "Acting",
            name: "Armand Aucamp",
            original_name: "Armand Aucamp",
            popularity: 3.64,
            profile_path: "/6scoxV13sTnnXFLqVNiHnJU53Yh.jpg",
          },
          {
            character: "Rika",
            credit_id: "64f0b42edbbb42013a22cf2d",
            order: 511,
            adult: false,
            gender: 1,
            id: 3859702,
            known_for_department: "Acting",
            name: "Kamdynn Gary",
            original_name: "Kamdynn Gary",
            popularity: 0.6,
            profile_path: "/4g97ms0dbKALnhgwSwwEXxZGV2k.jpg",
          },
          {
            character: "Mr. 7",
            credit_id: "64f0b4903a993700e2f7bc5e",
            order: 512,
            adult: false,
            gender: 0,
            id: 4245460,
            known_for_department: "Acting",
            name: "Ben Kgosimore",
            original_name: "Ben Kgosimore",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Cabaji",
            credit_id: "64f0b4a7ebb99d011d5aaa14",
            order: 513,
            adult: false,
            gender: 0,
            id: 4245461,
            known_for_department: "Acting",
            name: "Sven Ruygrok",
            original_name: "Sven Ruygrok",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Ririka",
            credit_id: "64f0b507e0ca7f012eb2719b",
            order: 514,
            adult: false,
            gender: 1,
            id: 1658759,
            known_for_department: "Acting",
            name: "Nicole Fortuin",
            original_name: "Nicole Fortuin",
            popularity: 1.596,
            profile_path: "/6YxW3hZANTmhrESXIdFtqvfIjtq.jpg",
          },
          {
            character: "Benn Beckman",
            credit_id: "64f0b51877d23b012e89f9d8",
            order: 515,
            adult: false,
            gender: 0,
            id: 1721959,
            known_for_department: "Acting",
            name: "Laudo Liebenberg",
            original_name: "Laudo Liebenberg",
            popularity: 0.84,
            profile_path: null,
          },
          {
            character: "Midshipman X",
            credit_id: "64f0b52aebb99d013bced32b",
            order: 516,
            adult: false,
            gender: 0,
            id: 4183048,
            known_for_department: "Acting",
            name: "Dale Lourens",
            original_name: "Dale Lourens",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Salvage Captain Wier",
            credit_id: "64f0b53fcaa50800c886e015",
            order: 517,
            adult: false,
            gender: 2,
            id: 1271727,
            known_for_department: "Acting",
            name: "Paul Snodgrass",
            original_name: "Paul Snodgrass",
            popularity: 1.4,
            profile_path: "/wtonOds5ugCg3jx9K3uDKs9uWcM.jpg",
          },
          {
            character: "Petty Officer Ukkari",
            credit_id: "64f0b5593a9937013929f99a",
            order: 518,
            adult: false,
            gender: 2,
            id: 2092570,
            known_for_department: "Acting",
            name: "Richard Wright-Firth",
            original_name: "Richard Wright-Firth",
            popularity: 0.6,
            profile_path: "/1VoTHiqhp1j3H5RwZcxNEcPHSBi.jpg",
          },
          {
            character: "Warrant Officer Sada",
            credit_id: "64f0b56897a4e600ac3e5b17",
            order: 519,
            adult: false,
            gender: 0,
            id: 4082692,
            known_for_department: "Acting",
            name: "Claire Glover",
            original_name: "Claire Glover",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Stripped Overalls",
            credit_id: "64f0b57acaa50800e951b8c0",
            order: 520,
            adult: false,
            gender: 2,
            id: 2387550,
            known_for_department: "Acting",
            name: "Sizo Mahlangu",
            original_name: "Sizo Mahlangu",
            popularity: 0.702,
            profile_path: "/otkOcNIjfw39XrwLnwnwlVfl7Tb.jpg",
          },
          {
            character: "Red Suspenders",
            credit_id: "64f0b597ebb99d011d5aaa63",
            order: 521,
            adult: false,
            gender: 0,
            id: 2092573,
            known_for_department: "Acting",
            name: "Greg Parvess",
            original_name: "Greg Parvess",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Heppoko",
            credit_id: "64f0b5d6ebb99d00c68c73d1",
            order: 522,
            adult: false,
            gender: 0,
            id: 3845388,
            known_for_department: "Acting",
            name: "Rendani Mufamadi",
            original_name: "Rendani Mufamadi",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Salvage Crew #1",
            credit_id: "64f0b5efebb99d00ad8bad98",
            order: 523,
            adult: false,
            gender: 0,
            id: 3921628,
            known_for_department: "Acting",
            name: "Ruari McKee",
            original_name: "Ruari McKee",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Salvage Crew #2",
            credit_id: "64f0b5fbdbbb4200c4ea2580",
            order: 524,
            adult: false,
            gender: 0,
            id: 4245470,
            known_for_department: "Acting",
            name: "Charl Atkinson",
            original_name: "Charl Atkinson",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Alvida Pirate #1",
            credit_id: "64f0b6173a993700e2f7bd21",
            order: 525,
            adult: false,
            gender: 0,
            id: 4245472,
            known_for_department: "Acting",
            name: "Apolinalho Antonio",
            original_name: "Apolinalho Antonio",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Alvida Pirate #2",
            credit_id: "64f0b622ebb99d00c68c73fe",
            order: 526,
            adult: false,
            gender: 0,
            id: 4245473,
            known_for_department: "Acting",
            name: "Steffan Stevens",
            original_name: "Steffan Stevens",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Alvida Pirate #3",
            credit_id: "64f0b63097a4e6013895cc50",
            order: 527,
            adult: false,
            gender: 0,
            id: 4245474,
            known_for_department: "Acting",
            name: "Martin Coetzee",
            original_name: "Martin Coetzee",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Young Mihawk",
            credit_id: "64f0b640dbbb4200ab5ec759",
            order: 528,
            adult: false,
            gender: 0,
            id: 4245475,
            known_for_department: "Acting",
            name: "Theo Le Ray",
            original_name: "Theo Le Ray",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Young Shanks",
            credit_id: "64f0b64de0ca7f014f6a4662",
            order: 529,
            adult: false,
            gender: 0,
            id: 4245476,
            known_for_department: "Acting",
            name: "Matt Herrington",
            original_name: "Matt Herrington",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Young Smoker",
            credit_id: "64f0b659e0ca7f010de3d0ff",
            order: 530,
            adult: false,
            gender: 0,
            id: 4245477,
            known_for_department: "Acting",
            name: "Matthew Leck",
            original_name: "Matthew Leck",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Loguetown Crowd Person #5",
            credit_id: "64f0b671ebb99d00e3e7ac26",
            order: 531,
            adult: false,
            gender: 0,
            id: 2144318,
            known_for_department: "Crew",
            name: "Tara Zulu",
            original_name: "Tara Zulu",
            popularity: 0.982,
            profile_path: null,
          },
          {
            character: "Loguetown Crowd Person #10",
            credit_id: "64f0b68377d23b00ec0432ab",
            order: 532,
            adult: false,
            gender: 0,
            id: 1333508,
            known_for_department: "Acting",
            name: "Sean Black",
            original_name: "Sean Black",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Captain Shanks",
            credit_id: "6504e99f394a87013914afee",
            order: 594,
            adult: false,
            gender: 2,
            id: 1035905,
            known_for_department: "Acting",
            name: "Peter Gadiot",
            original_name: "Peter Gadiot",
            popularity: 22.069,
            profile_path: "/462ODB50nmhpuXdpHz2otQ2rfOy.jpg",
          },
        ],
      },
      {
        air_date: "2023-08-31",
        episode_number: 2,
        episode_type: "standard",
        id: 4557389,
        name: "O homem do chapéu de palha",
        overview:
          "Após conseguirem o mapa da Grand Line, Luffy, Nami e Zoro enfrentam um palhaço que não está para brincadeira. O novo cadete Koby é encurralado pelo Vice-Almirante Garp.",
        production_code: "",
        runtime: 55,
        season_number: 1,
        show_id: 111110,
        still_path: "/fUYSyYPYCTB7bGuiqrwFQqt5xja.jpg",
        vote_average: 8.197,
        vote_count: 61,
        crew: [
          {
            job: "Director of Photography",
            department: "Camera",
            credit_id: "64de2289b77d4b11425f1108",
            adult: false,
            gender: 1,
            id: 225120,
            known_for_department: "Camera",
            name: "Nicole Hirsch Whitaker",
            original_name: "Nicole Hirsch Whitaker",
            popularity: 0.884,
            profile_path: null,
          },
          {
            job: "Director",
            department: "Directing",
            credit_id: "64de23a437109700ac442bd0",
            adult: false,
            gender: 2,
            id: 1515079,
            known_for_department: "Directing",
            name: "Marc Jobst",
            original_name: "Marc Jobst",
            popularity: 4.15,
            profile_path: null,
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de23b059e8a9011c8c04ae",
            adult: false,
            gender: 0,
            id: 1383187,
            known_for_department: "Writing",
            name: "Ian Stokes",
            original_name: "Ian Stokes",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04ce8dbbb42013a22a666",
            adult: false,
            gender: 2,
            id: 37003,
            known_for_department: "Editing",
            name: "Kevin D. Ross",
            original_name: "Kevin D. Ross",
            popularity: 2.744,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04cfcebb99d01008b13d5",
            adult: false,
            gender: 1,
            id: 1410314,
            known_for_department: "Editing",
            name: "Tessa Verfuss",
            original_name: "Tessa Verfuss",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04e23dbbb42011b708113",
            adult: false,
            gender: 0,
            id: 3358538,
            known_for_department: "Editing",
            name: "Daniel Williams",
            original_name: "Daniel Williams",
            popularity: 1.094,
            profile_path: null,
          },
        ],
        guest_stars: [
          {
            character: "Yasopp the Great",
            credit_id: "64f052a13a993700e2f78f92",
            order: 502,
            adult: false,
            gender: 0,
            id: 1184468,
            known_for_department: "Acting",
            name: "Stevel Marc",
            original_name: "Stevel Marc",
            popularity: 5.543,
            profile_path: "/n7NzuHjveJqZoEM5HFmblMGKdGp.jpg",
          },
          {
            character: "Lucky Roux",
            credit_id: "64f052c197a4e600fea874f1",
            order: 503,
            adult: false,
            gender: 2,
            id: 2340022,
            known_for_department: "Acting",
            name: "Ntlanhla Morgan Kutu",
            original_name: "Ntlanhla Morgan Kutu",
            popularity: 0.652,
            profile_path: "/c4wO2qJkVE24Wdc1Okz8zEB7gW6.jpg",
          },
          {
            character: "Young Luffy",
            credit_id: "64f0b3c1ebb99d00e3e7ab02",
            order: 506,
            adult: false,
            gender: 2,
            id: 2188198,
            known_for_department: "Acting",
            name: "Colton Osorio",
            original_name: "Colton Osorio",
            popularity: 24.608,
            profile_path: "/26QYXUN5sa6ZjFCy24y3nnL89SV.jpg",
          },
          {
            character: "Axe-Hand Morgan",
            credit_id: "64f0b3d7e0ca7f014f6a457b",
            order: 507,
            adult: false,
            gender: 2,
            id: 37093,
            known_for_department: "Acting",
            name: "Langley Kirkwood",
            original_name: "Langley Kirkwood",
            popularity: 8.414,
            profile_path: "/mtorXdi3X3v1V0KrrkUVfUAVQlX.jpg",
          },
          {
            character: "Higuma",
            credit_id: "64f0b3f877d23b0150390eff",
            order: 508,
            adult: false,
            gender: 2,
            id: 1838215,
            known_for_department: "Acting",
            name: "Tamer Burjaq",
            original_name: "Tamer Burjaq",
            popularity: 4.967,
            profile_path: "/rz1FOttxvkeVkAh7XxjBwd8eGgC.jpg",
          },
          {
            character: "Makino",
            credit_id: "64f0b40de0ca7f00ec86d76f",
            order: 509,
            adult: false,
            gender: 0,
            id: 4046635,
            known_for_department: "Acting",
            name: "Kathleen Stephens",
            original_name: "Kathleen Stephens",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Bogard",
            credit_id: "64f0b41d3a9937011cbdc02d",
            order: 510,
            adult: false,
            gender: 2,
            id: 1478709,
            known_for_department: "Acting",
            name: "Armand Aucamp",
            original_name: "Armand Aucamp",
            popularity: 3.64,
            profile_path: "/6scoxV13sTnnXFLqVNiHnJU53Yh.jpg",
          },
          {
            character: "Benn Beckman",
            credit_id: "64f0b51877d23b012e89f9d8",
            order: 515,
            adult: false,
            gender: 0,
            id: 1721959,
            known_for_department: "Acting",
            name: "Laudo Liebenberg",
            original_name: "Laudo Liebenberg",
            popularity: 0.84,
            profile_path: null,
          },
          {
            character: "Petty Officer Ukkari",
            credit_id: "64f0b5593a9937013929f99a",
            order: 518,
            adult: false,
            gender: 2,
            id: 2092570,
            known_for_department: "Acting",
            name: "Richard Wright-Firth",
            original_name: "Richard Wright-Firth",
            popularity: 0.6,
            profile_path: "/1VoTHiqhp1j3H5RwZcxNEcPHSBi.jpg",
          },
          {
            character: "Cabaji",
            credit_id: "64f0e761e0ca7f012eb280b8",
            order: 533,
            adult: false,
            gender: 2,
            id: 1003249,
            known_for_department: "Acting",
            name: "Sven Ruygrok",
            original_name: "Sven Ruygrok",
            popularity: 2.022,
            profile_path: "/dUr3VBQQ5n2nHmxkpsOnvBPm9Ri.jpg",
          },
          {
            character: "Mayor Boodle",
            credit_id: "64f0e79bdbbb42013a22df85",
            order: 534,
            adult: false,
            gender: 0,
            id: 1774135,
            known_for_department: "Acting",
            name: "Lindsay Reardon",
            original_name: "Lindsay Reardon",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #1",
            credit_id: "64f0eb9ccaa508010ae6bdb5",
            order: 535,
            adult: false,
            gender: 1,
            id: 4245881,
            known_for_department: "Acting",
            name: "Natasha Nova",
            original_name: "Natasha Nova",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #2",
            credit_id: "64f0eba7e0ca7f00cbe49261",
            order: 536,
            adult: false,
            gender: 0,
            id: 4216470,
            known_for_department: "Acting",
            name: "Tiaan Visser",
            original_name: "Tiaan Visser",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #3",
            credit_id: "64f0ebb2caa508010ae6bdc9",
            order: 537,
            adult: false,
            gender: 0,
            id: 4245882,
            known_for_department: "Acting",
            name: "Sam Pegg",
            original_name: "Sam Pegg",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #4",
            credit_id: "64f0ebc577d23b010d6bd2bb",
            order: 538,
            adult: false,
            gender: 0,
            id: 4245883,
            known_for_department: "Acting",
            name: "Abigail Martheze",
            original_name: "Abigail Martheze",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #5",
            credit_id: "64f0ebd4dbbb4200e1629bbd",
            order: 539,
            adult: false,
            gender: 0,
            id: 1532092,
            known_for_department: "Production",
            name: "Jacobus Kriel",
            original_name: "Jacobus Kriel",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #6",
            credit_id: "64f0ebe0caa50800c886f312",
            order: 540,
            adult: false,
            gender: 0,
            id: 3504089,
            known_for_department: "Production",
            name: "Wendy Acton",
            original_name: "Wendy Acton",
            popularity: 0.98,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #7",
            credit_id: "64f0ebec5f2b8d011b4cd4d6",
            order: 541,
            adult: false,
            gender: 0,
            id: 4245884,
            known_for_department: "Acting",
            name: "Zwelakhe Moni",
            original_name: "Zwelakhe Moni",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #8",
            credit_id: "64f0ebf797a4e6013895decf",
            order: 542,
            adult: false,
            gender: 2,
            id: 953772,
            known_for_department: "Acting",
            name: "Farouk Valley-Omar",
            original_name: "Farouk Valley-Omar",
            popularity: 5.195,
            profile_path: "/8tUv6cKFyRBjxiEt74DGIocMUwf.jpg",
          },
          {
            character: "Buggy's Captive #9",
            credit_id: "64f0ec0977d23b012e8a0999",
            order: 543,
            adult: false,
            gender: 0,
            id: 4245887,
            known_for_department: "Acting",
            name: "Nolufefe Lujabe",
            original_name: "Nolufefe Lujabe",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #10",
            credit_id: "64f0ec1acaa50800ab71f635",
            order: 544,
            adult: false,
            gender: 0,
            id: 4245889,
            known_for_department: "Acting",
            name: "Nolan Africa",
            original_name: "Nolan Africa",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #11",
            credit_id: "64f0ec2735039800c7a47774",
            order: 545,
            adult: false,
            gender: 0,
            id: 4245890,
            known_for_department: "Acting",
            name: "Derek Van Niekerk",
            original_name: "Derek Van Niekerk",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #12",
            credit_id: "64f0ec3a97a4e6011baf8d41",
            order: 546,
            adult: false,
            gender: 0,
            id: 1824586,
            known_for_department: "Acting",
            name: "Geoffrey Downes",
            original_name: "Geoffrey Downes",
            popularity: 0.98,
            profile_path: null,
          },
          {
            character: "Buggy's Captive #13",
            credit_id: "64f0ec4fdbbb4200ab5ed8c0",
            order: 547,
            adult: false,
            gender: 0,
            id: 4245891,
            known_for_department: "Acting",
            name: "Kim Yang",
            original_name: "Kim Yang",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Captain Shanks",
            credit_id: "6504e99f394a87013914afee",
            order: 594,
            adult: false,
            gender: 2,
            id: 1035905,
            known_for_department: "Acting",
            name: "Peter Gadiot",
            original_name: "Peter Gadiot",
            popularity: 22.069,
            profile_path: "/462ODB50nmhpuXdpHz2otQ2rfOy.jpg",
          },
        ],
      },
      {
        air_date: "2023-08-31",
        episode_number: 3,
        episode_type: "standard",
        id: 4557390,
        name: "O contador de histórias",
        overview:
          "Em busca de um navio, o grupo chega à Vila Syrup e encontra o animado Usopp e sua amiga Kaya. Mas uma ameaça sinistra atrapalha os planos.",
        production_code: "",
        runtime: 58,
        season_number: 1,
        show_id: 111110,
        still_path: "/71U4bl7z63ZGF5n2stJ7paELeNQ.jpg",
        vote_average: 8.128,
        vote_count: 39,
        crew: [
          {
            job: "Director of Photography",
            department: "Camera",
            credit_id: "64de22d337109700ac442b67",
            adult: false,
            gender: 2,
            id: 2112267,
            known_for_department: "Camera",
            name: "Michael Wood",
            original_name: "Michael Wood",
            popularity: 0.728,
            profile_path: null,
          },
          {
            job: "Director",
            department: "Directing",
            credit_id: "64de23c0aaec7103fa477885",
            adult: false,
            gender: 1,
            id: 1875947,
            known_for_department: "Directing",
            name: "Emma Sullivan",
            original_name: "Emma Sullivan",
            popularity: 1.27,
            profile_path: "/mlljDecXTk1Vm8KlMykclr1RvQU.jpg",
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de23ca59e8a90139d6f800",
            adult: false,
            gender: 2,
            id: 1562489,
            known_for_department: "Writing",
            name: "Matt Owens",
            original_name: "Matt Owens",
            popularity: 2.65,
            profile_path: "/9557f2EgDxHEhnXmXf6Hx9io76S.jpg",
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de23d1b77d4b114019b810",
            adult: false,
            gender: 0,
            id: 2082297,
            known_for_department: "Writing",
            name: "Damani Johnson",
            original_name: "Damani Johnson",
            popularity: 1.4,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04d3a97a4e600ac3e3590",
            adult: false,
            gender: 0,
            id: 3946733,
            known_for_department: "Editing",
            name: "Eric Litman",
            original_name: "Eric Litman",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Graphic Designer",
            department: "Art",
            credit_id: "64f134b0e0ca7f014f6a7790",
            adult: false,
            gender: 0,
            id: 3932772,
            known_for_department: "Art",
            name: "Emlyn Nield",
            original_name: "Emlyn Nield",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Conceptual Illustrator",
            department: "Art",
            credit_id: "64f134de3a993700e2f7f57d",
            adult: false,
            gender: 0,
            id: 2143747,
            known_for_department: "Costume & Make-Up",
            name: "Deon de Lange",
            original_name: "Deon de Lange",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Clearances Coordinator",
            department: "Crew",
            credit_id: "64f1351edbbb42013a2300f7",
            adult: false,
            gender: 0,
            id: 2000354,
            known_for_department: "Art",
            name: "Jacques Van Rooyen",
            original_name: "Jacques Van Rooyen",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Wigmaker",
            department: "Costume & Make-Up",
            credit_id: "64f135a7caa50800c8871999",
            adult: false,
            gender: 1,
            id: 2101045,
            known_for_department: "Costume & Make-Up",
            name: "Odette Rebok",
            original_name: "Odette Rebok",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Stunt Coordinator",
            department: "Crew",
            credit_id: "64f135fecaa50800ab721656",
            adult: false,
            gender: 2,
            id: 2101023,
            known_for_department: "Crew",
            name: "Darrell McLean",
            original_name: "Darrell McLean",
            popularity: 1.4,
            profile_path: null,
          },
        ],
        guest_stars: [
          {
            character: "Bogard",
            credit_id: "64f0b41d3a9937011cbdc02d",
            order: 510,
            adult: false,
            gender: 2,
            id: 1478709,
            known_for_department: "Acting",
            name: "Armand Aucamp",
            original_name: "Armand Aucamp",
            popularity: 3.64,
            profile_path: "/6scoxV13sTnnXFLqVNiHnJU53Yh.jpg",
          },
          {
            character: "Captain Arlong",
            credit_id: "64f1339597a4e600ac3e8a50",
            order: 548,
            adult: false,
            gender: 2,
            id: 1493226,
            known_for_department: "Acting",
            name: "McKinley Belcher III",
            original_name: "McKinley Belcher III",
            popularity: 21.185,
            profile_path: "/yoglJWyhgA1tnqQS9T3MQPPEsRc.jpg",
          },
          {
            character: "Kaya",
            credit_id: "64f133b177d23b010d6bf263",
            order: 549,
            adult: false,
            gender: 1,
            id: 3456853,
            known_for_department: "Acting",
            name: "Celeste Loots",
            original_name: "Celeste Loots",
            popularity: 0.732,
            profile_path: "/fbUO4PSWS2qzyaVUZkNSzZWe4xt.jpg",
          },
          {
            character: "Klahadore",
            credit_id: "64f133bfe0ca7f010de40202",
            order: 550,
            adult: false,
            gender: 2,
            id: 3361078,
            known_for_department: "Acting",
            name: "Alexander Maniatis",
            original_name: "Alexander Maniatis",
            popularity: 3.634,
            profile_path: "/2KWPtbO7zqUlvzplRobIcHvUDch.jpg",
          },
          {
            character: "Sham",
            credit_id: "64f133d1caa508012b068bc1",
            order: 551,
            adult: false,
            gender: 1,
            id: 3623909,
            known_for_department: "Acting",
            name: "Bianca Oosthuizen",
            original_name: "Bianca Oosthuizen",
            popularity: 0.835,
            profile_path: "/o0m0pwMIaENUnCz4qNzIZ83og6e.jpg",
          },
          {
            character: "Buchi",
            credit_id: "64f133e7dbbb4200c4ea57ba",
            order: 552,
            adult: false,
            gender: 2,
            id: 1154503,
            known_for_department: "Acting",
            name: "Albert Pretorius",
            original_name: "Albert Pretorius",
            popularity: 3.486,
            profile_path: "/2kOCpuPGiAD4DhOYnBlgHT6kMZ8.jpg",
          },
          {
            character: "Kuroobi",
            credit_id: "64f133f877d23b00cb862aef",
            order: 553,
            adult: false,
            gender: 2,
            id: 1863259,
            known_for_department: "Acting",
            name: "Jandre le Roux",
            original_name: "Jandre le Roux",
            popularity: 3.906,
            profile_path: "/jZZvq9scQReLz04uCzyaayu959g.jpg",
          },
          {
            character: "Merry",
            credit_id: "64f1341a97a4e6011bafae5c",
            order: 554,
            adult: false,
            gender: 2,
            id: 98414,
            known_for_department: "Acting",
            name: "Brett Williams",
            original_name: "Brett Williams",
            popularity: 7.309,
            profile_path: "/4x9HH4oBw2UVqb4TOCNuXfmgjVH.jpg",
          },
          {
            character: "Banchina",
            credit_id: "64f1345d3a993701392a2e76",
            order: 555,
            adult: false,
            gender: 0,
            id: 4216396,
            known_for_department: "Acting",
            name: "Chante Grainger",
            original_name: "Chante Grainger",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Mornin",
            credit_id: "64f13472dbbb4200ab5efade",
            order: 556,
            adult: false,
            gender: 2,
            id: 1944438,
            known_for_department: "Acting",
            name: "Nicky Rebelo",
            original_name: "Nicky Rebelo",
            popularity: 1.96,
            profile_path: "/f0pkFEpwQ1E9EppUuuw6FWXzR5I.jpg",
          },
          {
            character: "Captain Shanks",
            credit_id: "6504e99f394a87013914afee",
            order: 594,
            adult: false,
            gender: 2,
            id: 1035905,
            known_for_department: "Acting",
            name: "Peter Gadiot",
            original_name: "Peter Gadiot",
            popularity: 22.069,
            profile_path: "/462ODB50nmhpuXdpHz2otQ2rfOy.jpg",
          },
          {
            character: "Usopp",
            credit_id: "6512220426dac1014e232b75",
            order: 596,
            adult: false,
            gender: 2,
            id: 2355316,
            known_for_department: "Acting",
            name: "Jacob Gibson",
            original_name: "Jacob Gibson",
            popularity: 31.665,
            profile_path: "/foaSZvcg70p2gxiJxqtGo3YqWIC.jpg",
          },
        ],
      },
      {
        air_date: "2023-08-31",
        episode_number: 4,
        episode_type: "standard",
        id: 4557391,
        name: "Os piratas estão vindo",
        overview:
          "Com os amigos em perigo e o plano de Klahador em ação, Usopp pede ajuda à Marinha. O clima esquenta em uma batalha na mansão de Kaya.",
        production_code: "",
        runtime: 62,
        season_number: 1,
        show_id: 111110,
        still_path: "/94TQgW3NgeaEXsugrlcwbpGiIb3.jpg",
        vote_average: 7.969,
        vote_count: 32,
        crew: [
          {
            job: "Director of Photography",
            department: "Camera",
            credit_id: "64de22d337109700ac442b67",
            adult: false,
            gender: 2,
            id: 2112267,
            known_for_department: "Camera",
            name: "Michael Wood",
            original_name: "Michael Wood",
            popularity: 0.728,
            profile_path: null,
          },
          {
            job: "Director",
            department: "Directing",
            credit_id: "64de23c0aaec7103fa477885",
            adult: false,
            gender: 1,
            id: 1875947,
            known_for_department: "Directing",
            name: "Emma Sullivan",
            original_name: "Emma Sullivan",
            popularity: 1.27,
            profile_path: "/mlljDecXTk1Vm8KlMykclr1RvQU.jpg",
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de23eb37109700ffb917c6",
            adult: false,
            gender: 0,
            id: 1457979,
            known_for_department: "Writing",
            name: "Tiffany Greshler",
            original_name: "Tiffany Greshler",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de23f3a3b5e600ff4d6cbe",
            adult: false,
            gender: 0,
            id: 2546214,
            known_for_department: "Writing",
            name: "Tom Hyndman",
            original_name: "Tom Hyndman",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04d3a97a4e600ac3e3590",
            adult: false,
            gender: 0,
            id: 3946733,
            known_for_department: "Editing",
            name: "Eric Litman",
            original_name: "Eric Litman",
            popularity: 0.6,
            profile_path: null,
          },
        ],
        guest_stars: [
          {
            character: "Bogard",
            credit_id: "64f0b41d3a9937011cbdc02d",
            order: 510,
            adult: false,
            gender: 2,
            id: 1478709,
            known_for_department: "Acting",
            name: "Armand Aucamp",
            original_name: "Armand Aucamp",
            popularity: 3.64,
            profile_path: "/6scoxV13sTnnXFLqVNiHnJU53Yh.jpg",
          },
          {
            character: "Kaya",
            credit_id: "64f133b177d23b010d6bf263",
            order: 549,
            adult: false,
            gender: 1,
            id: 3456853,
            known_for_department: "Acting",
            name: "Celeste Loots",
            original_name: "Celeste Loots",
            popularity: 0.732,
            profile_path: "/fbUO4PSWS2qzyaVUZkNSzZWe4xt.jpg",
          },
          {
            character: "Klahadore",
            credit_id: "64f133bfe0ca7f010de40202",
            order: 550,
            adult: false,
            gender: 2,
            id: 3361078,
            known_for_department: "Acting",
            name: "Alexander Maniatis",
            original_name: "Alexander Maniatis",
            popularity: 3.634,
            profile_path: "/2KWPtbO7zqUlvzplRobIcHvUDch.jpg",
          },
          {
            character: "Sham",
            credit_id: "64f133d1caa508012b068bc1",
            order: 551,
            adult: false,
            gender: 1,
            id: 3623909,
            known_for_department: "Acting",
            name: "Bianca Oosthuizen",
            original_name: "Bianca Oosthuizen",
            popularity: 0.835,
            profile_path: "/o0m0pwMIaENUnCz4qNzIZ83og6e.jpg",
          },
          {
            character: "Buchi",
            credit_id: "64f133e7dbbb4200c4ea57ba",
            order: 552,
            adult: false,
            gender: 2,
            id: 1154503,
            known_for_department: "Acting",
            name: "Albert Pretorius",
            original_name: "Albert Pretorius",
            popularity: 3.486,
            profile_path: "/2kOCpuPGiAD4DhOYnBlgHT6kMZ8.jpg",
          },
          {
            character: "Merry",
            credit_id: "64f1341a97a4e6011bafae5c",
            order: 554,
            adult: false,
            gender: 2,
            id: 98414,
            known_for_department: "Acting",
            name: "Brett Williams",
            original_name: "Brett Williams",
            popularity: 7.309,
            profile_path: "/4x9HH4oBw2UVqb4TOCNuXfmgjVH.jpg",
          },
          {
            character: "Young Zoro",
            credit_id: "64f31c051f3319011d1666d9",
            order: 557,
            adult: false,
            gender: 2,
            id: 3218113,
            known_for_department: "Acting",
            name: "Maximilian Lee Piazza",
            original_name: "Maximilian Lee Piazza",
            popularity: 1.984,
            profile_path: "/m0eVy4H0aX9XxzrSFxzXsU2qfuL.jpg",
          },
          {
            character: "Shimotsuki Kuina",
            credit_id: "64f31c111f331900ad472e72",
            order: 558,
            adult: false,
            gender: 0,
            id: 3334448,
            known_for_department: "Acting",
            name: "Audrey Cymone",
            original_name: "Audrey Cymone",
            popularity: 0.98,
            profile_path: "/b9rJTHo1m9T2Xy1KBAKjuhdBpxl.jpg",
          },
          {
            character: "Koushirou",
            credit_id: "64f31c4e74507d00adc15bc2",
            order: 559,
            adult: false,
            gender: 2,
            id: 3052852,
            known_for_department: "Acting",
            name: "Nathan Castle",
            original_name: "Nathan Castle",
            popularity: 1.094,
            profile_path: "/aTk8drkQ0quStkcay5CNsWKImWf.jpg",
          },
          {
            character: "Usopp",
            credit_id: "6512220426dac1014e232b75",
            order: 596,
            adult: false,
            gender: 2,
            id: 2355316,
            known_for_department: "Acting",
            name: "Jacob Gibson",
            original_name: "Jacob Gibson",
            popularity: 31.665,
            profile_path: "/foaSZvcg70p2gxiJxqtGo3YqWIC.jpg",
          },
        ],
      },
      {
        air_date: "2023-08-31",
        episode_number: 5,
        episode_type: "standard",
        id: 4557392,
        name: "Venha comer no Baratie!",
        overview:
          "O Bando do Chapéu de Palha enfrenta o primeiro adversário. Num restaurante flutuante, Luffy faz amizade com um cozinheiro, e Zoro se envolve em um duelo.",
        production_code: "",
        runtime: 51,
        season_number: 1,
        show_id: 111110,
        still_path: "/6nJBXGTN1ig4whalJvaWA2vyAgr.jpg",
        vote_average: 7.889,
        vote_count: 45,
        crew: [
          {
            job: "Director",
            department: "Directing",
            credit_id: "64de23fca3b5e6011c404797",
            adult: false,
            gender: 2,
            id: 537105,
            known_for_department: "Directing",
            name: "Tim Southam",
            original_name: "Tim Southam",
            popularity: 2.031,
            profile_path: null,
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de2409d100b614b4ccdaa6",
            adult: false,
            gender: 0,
            id: 1881760,
            known_for_department: "Writing",
            name: "Laura Jacqmin",
            original_name: "Laura Jacqmin",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04cfcebb99d01008b13d5",
            adult: false,
            gender: 1,
            id: 1410314,
            known_for_department: "Editing",
            name: "Tessa Verfuss",
            original_name: "Tessa Verfuss",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Director of Photography",
            department: "Camera",
            credit_id: "64f0508c97a4e600ac3e36f1",
            adult: false,
            gender: 2,
            id: 135388,
            known_for_department: "Camera",
            name: "Michael Swan",
            original_name: "Michael Swan",
            popularity: 0.6,
            profile_path: null,
          },
        ],
        guest_stars: [
          {
            character: "Young Luffy",
            credit_id: "64f0b3c1ebb99d00e3e7ab02",
            order: 506,
            adult: false,
            gender: 2,
            id: 2188198,
            known_for_department: "Acting",
            name: "Colton Osorio",
            original_name: "Colton Osorio",
            popularity: 24.608,
            profile_path: "/26QYXUN5sa6ZjFCy24y3nnL89SV.jpg",
          },
          {
            character: "Bogard",
            credit_id: "64f0b41d3a9937011cbdc02d",
            order: 510,
            adult: false,
            gender: 2,
            id: 1478709,
            known_for_department: "Acting",
            name: "Armand Aucamp",
            original_name: "Armand Aucamp",
            popularity: 3.64,
            profile_path: "/6scoxV13sTnnXFLqVNiHnJU53Yh.jpg",
          },
          {
            character: "Zeff",
            credit_id: "64f31eb577d23b012e8af0a5",
            order: 560,
            adult: false,
            gender: 2,
            id: 51799,
            known_for_department: "Acting",
            name: "Craig Fairbrass",
            original_name: "Craig Fairbrass",
            popularity: 13.016,
            profile_path: "/z5WnSqwkM0Ax0Z47etVNmcew5Pn.jpg",
          },
          {
            character: "Dracule Mihawk",
            credit_id: "64f31ee1e0ca7f010de4e1f6",
            order: 561,
            adult: false,
            gender: 2,
            id: 1644383,
            known_for_department: "Acting",
            name: "Steven John Ward",
            original_name: "Steven John Ward",
            popularity: 2.318,
            profile_path: "/ssHvaa88N8JdraA76filDejf9jK.jpg",
          },
          {
            character: "Don Krieg",
            credit_id: "64f31f0b97a4e600e1a3f9f3",
            order: 562,
            adult: false,
            gender: 2,
            id: 1988045,
            known_for_department: "Acting",
            name: "Milton Schorr",
            original_name: "Milton Schorr",
            popularity: 4.864,
            profile_path: "/tKrRpxUGTDCoDlSenhf3Xl7AAal.jpg",
          },
          {
            character: "Bartender",
            credit_id: "64f31f6074507d011c1ef164",
            order: 564,
            adult: false,
            gender: 0,
            id: 4248879,
            known_for_department: "Acting",
            name: "Matt von Zweigbergk",
            original_name: "Matt von Zweigbergk",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Gin",
            credit_id: "64f31f6c74507d00c513359e",
            order: 565,
            adult: false,
            gender: 2,
            id: 2764822,
            known_for_department: "Acting",
            name: "Litha Bam",
            original_name: "Litha Bam",
            popularity: 0.6,
            profile_path: "/1B3q4D6YhfPk7TBVx8nXDJawRJB.jpg",
          },
          {
            character: "Patty",
            credit_id: "64f31f77e0ca7f012eb37e9f",
            order: 566,
            adult: false,
            gender: 2,
            id: 1509227,
            known_for_department: "Acting",
            name: "Brashaad Mayweather",
            original_name: "Brashaad Mayweather",
            popularity: 1.276,
            profile_path: "/lKKMyDWRTmp7cuo3l2HPJuQrn8E.jpg",
          },
          {
            character: "Maître d' / Trader",
            credit_id: "64f31f85e0ca7f00ec87ddef",
            order: 567,
            adult: false,
            gender: 2,
            id: 980004,
            known_for_department: "Acting",
            name: "Royston Stoffels",
            original_name: "Royston Stoffels",
            popularity: 1.571,
            profile_path: "/bOUapLQxeVJpTP2znmbQFhsaOTs.jpg",
          },
          {
            character: "Full Body (Patron at Baratie)",
            credit_id: "64f31f9f5f2b8d00e12b8543",
            order: 568,
            adult: false,
            gender: 0,
            id: 1693191,
            known_for_department: "Acting",
            name: "Jean Henry",
            original_name: "Jean Henry",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Gully (Patron at Baratie)",
            credit_id: "64f31fb9e0ca7f010de4e265",
            order: 569,
            adult: false,
            gender: 0,
            id: 4248880,
            known_for_department: "Acting",
            name: "Nkululeko Chunky Phiri",
            original_name: "Nkululeko Chunky Phiri",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Usopp",
            credit_id: "6512220426dac1014e232b75",
            order: 596,
            adult: false,
            gender: 2,
            id: 2355316,
            known_for_department: "Acting",
            name: "Jacob Gibson",
            original_name: "Jacob Gibson",
            popularity: 31.665,
            profile_path: "/foaSZvcg70p2gxiJxqtGo3YqWIC.jpg",
          },
        ],
      },
      {
        air_date: "2023-08-31",
        episode_number: 6,
        episode_type: "standard",
        id: 4557393,
        name: "O chef e o faz-tudo",
        overview:
          "Sanji e o chef Zeff deixam as diferenças de lado para salvar Zoro, que está gravemente ferido. Um homem-peixe implacável causa problemas para a tripulação.",
        production_code: "",
        runtime: 54,
        season_number: 1,
        show_id: 111110,
        still_path: "/lZgNsaPEIrvXi2InAlilH51EGZA.jpg",
        vote_average: 8.25,
        vote_count: 28,
        crew: [
          {
            job: "Director",
            department: "Directing",
            credit_id: "64de23fca3b5e6011c404797",
            adult: false,
            gender: 2,
            id: 537105,
            known_for_department: "Directing",
            name: "Tim Southam",
            original_name: "Tim Southam",
            popularity: 2.031,
            profile_path: null,
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de2417d100b614b2ef72c8",
            adult: false,
            gender: 2,
            id: 1225826,
            known_for_department: "Writing",
            name: "Steven Maeda",
            original_name: "Steven Maeda",
            popularity: 2.545,
            profile_path: "/4QwZvyeiOOsIy3jhtLgS5iy7Whw.jpg",
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de24245ab81a01391950e3",
            adult: false,
            gender: 2,
            id: 1215764,
            known_for_department: "Writing",
            name: "Diego Gutierrez",
            original_name: "Diego Gutierrez",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04cfcebb99d01008b13d5",
            adult: false,
            gender: 1,
            id: 1410314,
            known_for_department: "Editing",
            name: "Tessa Verfuss",
            original_name: "Tessa Verfuss",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Director of Photography",
            department: "Camera",
            credit_id: "64f0508c97a4e600ac3e36f1",
            adult: false,
            gender: 2,
            id: 135388,
            known_for_department: "Camera",
            name: "Michael Swan",
            original_name: "Michael Swan",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f0512b77d23b00aebee7fd",
            adult: false,
            gender: 2,
            id: 1115251,
            known_for_department: "Editing",
            name: "Tim Kinzy",
            original_name: "Tim Kinzy",
            popularity: 0.6,
            profile_path: null,
          },
        ],
        guest_stars: [
          {
            character: "Bogard",
            credit_id: "64f0b41d3a9937011cbdc02d",
            order: 510,
            adult: false,
            gender: 2,
            id: 1478709,
            known_for_department: "Acting",
            name: "Armand Aucamp",
            original_name: "Armand Aucamp",
            popularity: 3.64,
            profile_path: "/6scoxV13sTnnXFLqVNiHnJU53Yh.jpg",
          },
          {
            character: "Captain Arlong",
            credit_id: "64f1339597a4e600ac3e8a50",
            order: 548,
            adult: false,
            gender: 2,
            id: 1493226,
            known_for_department: "Acting",
            name: "McKinley Belcher III",
            original_name: "McKinley Belcher III",
            popularity: 21.185,
            profile_path: "/yoglJWyhgA1tnqQS9T3MQPPEsRc.jpg",
          },
          {
            character: "Kuroobi",
            credit_id: "64f133f877d23b00cb862aef",
            order: 553,
            adult: false,
            gender: 2,
            id: 1863259,
            known_for_department: "Acting",
            name: "Jandre le Roux",
            original_name: "Jandre le Roux",
            popularity: 3.906,
            profile_path: "/jZZvq9scQReLz04uCzyaayu959g.jpg",
          },
          {
            character: "Zeff",
            credit_id: "64f31eb577d23b012e8af0a5",
            order: 560,
            adult: false,
            gender: 2,
            id: 51799,
            known_for_department: "Acting",
            name: "Craig Fairbrass",
            original_name: "Craig Fairbrass",
            popularity: 13.016,
            profile_path: "/z5WnSqwkM0Ax0Z47etVNmcew5Pn.jpg",
          },
          {
            character: "Dracule Mihawk",
            credit_id: "64f31ee1e0ca7f010de4e1f6",
            order: 561,
            adult: false,
            gender: 2,
            id: 1644383,
            known_for_department: "Acting",
            name: "Steven John Ward",
            original_name: "Steven John Ward",
            popularity: 2.318,
            profile_path: "/ssHvaa88N8JdraA76filDejf9jK.jpg",
          },
          {
            character: "Maître d'",
            credit_id: "64f31f451f33190100a4eda0",
            order: 563,
            adult: false,
            gender: 2,
            id: 980004,
            known_for_department: "Acting",
            name: "Royston Stoffels",
            original_name: "Royston Stoffels",
            popularity: 1.571,
            profile_path: "/bOUapLQxeVJpTP2znmbQFhsaOTs.jpg",
          },
          {
            character: "Patty",
            credit_id: "64f31f77e0ca7f012eb37e9f",
            order: 566,
            adult: false,
            gender: 2,
            id: 1509227,
            known_for_department: "Acting",
            name: "Brashaad Mayweather",
            original_name: "Brashaad Mayweather",
            popularity: 1.276,
            profile_path: "/lKKMyDWRTmp7cuo3l2HPJuQrn8E.jpg",
          },
          {
            character: "Young Sanji",
            credit_id: "64f321f474507d00e2ba735b",
            order: 570,
            adult: false,
            gender: 2,
            id: 1721268,
            known_for_department: "Acting",
            name: "Christian Convery",
            original_name: "Christian Convery",
            popularity: 12.399,
            profile_path: "/c1l5tNjmxzDAIaTHvzEfooUsAf8.jpg",
          },
          {
            character: "Chew",
            credit_id: "64f3224be0ca7f012eb37fba",
            order: 571,
            adult: false,
            gender: 0,
            id: 2943486,
            known_for_department: "Acting",
            name: "Len-Barry Simons",
            original_name: "Len-Barry Simons",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Meshi",
            credit_id: "64f322b297a4e600c487cd89",
            order: 572,
            adult: false,
            gender: 0,
            id: 1360630,
            known_for_department: "Acting",
            name: "Andrew Roux",
            original_name: "Andrew Roux",
            popularity: 0.985,
            profile_path: "/dmBDN9adUOlsqmxuqI0qSJnDPIH.jpg",
          },
          {
            character: "Motzel",
            credit_id: "64f322be1f3319011d166913",
            order: 573,
            adult: false,
            gender: 2,
            id: 83154,
            known_for_department: "Acting",
            name: "David Muller",
            original_name: "David Muller",
            popularity: 1.4,
            profile_path: null,
          },
          {
            character: "Baratie Patron #1",
            credit_id: "64f322db1f331900c6f5ace8",
            order: 574,
            adult: false,
            gender: 0,
            id: 4248893,
            known_for_department: "Acting",
            name: "Patricia Sanqela",
            original_name: "Patricia Sanqela",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Baratie Patron #2",
            credit_id: "64f322e377d23b00aec0079d",
            order: 575,
            adult: false,
            gender: 0,
            id: 4216549,
            known_for_department: "Acting",
            name: "Huram Louw",
            original_name: "Huram Louw",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Baratie Patron #3",
            credit_id: "64f322ed5f2b8d0139ce01e0",
            order: 576,
            adult: false,
            gender: 0,
            id: 4248894,
            known_for_department: "Acting",
            name: "Khaya Sihamba",
            original_name: "Khaya Sihamba",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Baratie Patron #4",
            credit_id: "64f322f81f331900c6f5acfd",
            order: 577,
            adult: false,
            gender: 0,
            id: 4248895,
            known_for_department: "Acting",
            name: "Hennie Kotze",
            original_name: "Hennie Kotze",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Baratie Patron #5",
            credit_id: "64f3231bcaa50800c8881880",
            order: 578,
            adult: false,
            gender: 0,
            id: 4248896,
            known_for_department: "Acting",
            name: "Kyra Swart",
            original_name: "Kyra Swart",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Baratie Patron #6",
            credit_id: "64f3232577d23b015039e80a",
            order: 579,
            adult: false,
            gender: 0,
            id: 4248897,
            known_for_department: "Acting",
            name: "Ross van Leeve",
            original_name: "Ross van Leeve",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Baratie Patron #7",
            credit_id: "64f323311f331900e356a5f7",
            order: 580,
            adult: false,
            gender: 0,
            id: 4248898,
            known_for_department: "Acting",
            name: "Ellen Nel",
            original_name: "Ellen Nel",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Baratie Patron #8",
            credit_id: "64f3233c1f331900c6f5ad27",
            order: 581,
            adult: false,
            gender: 1,
            id: 2155493,
            known_for_department: "Acting",
            name: "Sharon Waugh",
            original_name: "Sharon Waugh",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Baratie Patron #9",
            credit_id: "64f3234777d23b010d6cdaa5",
            order: 582,
            adult: false,
            gender: 0,
            id: 4248899,
            known_for_department: "Acting",
            name: "Lynette Ou Tim",
            original_name: "Lynette Ou Tim",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Usopp",
            credit_id: "6512220426dac1014e232b75",
            order: 596,
            adult: false,
            gender: 2,
            id: 2355316,
            known_for_department: "Acting",
            name: "Jacob Gibson",
            original_name: "Jacob Gibson",
            popularity: 31.665,
            profile_path: "/foaSZvcg70p2gxiJxqtGo3YqWIC.jpg",
          },
        ],
      },
      {
        air_date: "2023-08-31",
        episode_number: 7,
        episode_type: "standard",
        id: 4557394,
        name: "A garota com a tatuagem de peixe-serra",
        overview:
          "Após fazer um acordo com um velho inimigo para encontrar Arlong, Luffy e seus amigos navegam até a Vila Cocoyashi e descobrem o passado misterioso de Nami.",
        production_code: "",
        runtime: 58,
        season_number: 1,
        show_id: 111110,
        still_path: "/828JBjk9zrKbMQgdp6oHrRog0WY.jpg",
        vote_average: 7.9,
        vote_count: 30,
        crew: [
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de23b059e8a9011c8c04ae",
            adult: false,
            gender: 0,
            id: 1383187,
            known_for_department: "Writing",
            name: "Ian Stokes",
            original_name: "Ian Stokes",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de23eb37109700ffb917c6",
            adult: false,
            gender: 0,
            id: 1457979,
            known_for_department: "Writing",
            name: "Tiffany Greshler",
            original_name: "Tiffany Greshler",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Director",
            department: "Directing",
            credit_id: "64de24e85ab81a011c2df167",
            adult: false,
            gender: 2,
            id: 1304310,
            known_for_department: "Directing",
            name: "Josef Wladyka",
            original_name: "Josef Wladyka",
            popularity: 5.991,
            profile_path: "/jDwJssEia8lVh5MLvuAI3vDm3jv.jpg",
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de2507a3b5e6013900bce6",
            adult: false,
            gender: 0,
            id: 1498436,
            known_for_department: "Writing",
            name: "Allison Weintraub",
            original_name: "Allison Weintraub",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de250db77d4b113e0644b1",
            adult: false,
            gender: 0,
            id: 1826222,
            known_for_department: "Writing",
            name: "Lindsay Gelfand",
            original_name: "Lindsay Gelfand",
            popularity: 0.6,
            profile_path: null,
          },
          {
            job: "Director of Photography",
            department: "Camera",
            credit_id: "64f04bcc4b0c6300abaae2ef",
            adult: false,
            gender: 2,
            id: 1393366,
            known_for_department: "Camera",
            name: "Trevor Michael Brown",
            original_name: "Trevor Michael Brown",
            popularity: 1.614,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04be677d23b015038ee93",
            adult: false,
            gender: 0,
            id: 62702,
            known_for_department: "Editing",
            name: "Tirsa Hackshaw",
            original_name: "Tirsa Hackshaw",
            popularity: 1.4,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f051d94b0c6300abaae592",
            adult: false,
            gender: 1,
            id: 2513423,
            known_for_department: "Editing",
            name: "Marie Lee",
            original_name: "Marie Lee",
            popularity: 0.6,
            profile_path: null,
          },
        ],
        guest_stars: [
          {
            character: "Captain Nezumi",
            credit_id: "64f0527497a4e600c4869d48",
            order: 501,
            adult: false,
            gender: 2,
            id: 30036,
            known_for_department: "Acting",
            name: "Rory Acton Burnell",
            original_name: "Rory Acton Burnell",
            popularity: 17.413,
            profile_path: "/qxar3nAYjR6Mp5hTcjy1HEckgbP.jpg",
          },
          {
            character: "Bogard",
            credit_id: "64f0b41d3a9937011cbdc02d",
            order: 510,
            adult: false,
            gender: 2,
            id: 1478709,
            known_for_department: "Acting",
            name: "Armand Aucamp",
            original_name: "Armand Aucamp",
            popularity: 3.64,
            profile_path: "/6scoxV13sTnnXFLqVNiHnJU53Yh.jpg",
          },
          {
            character: "Captain Arlong",
            credit_id: "64f1339597a4e600ac3e8a50",
            order: 548,
            adult: false,
            gender: 2,
            id: 1493226,
            known_for_department: "Acting",
            name: "McKinley Belcher III",
            original_name: "McKinley Belcher III",
            popularity: 21.185,
            profile_path: "/yoglJWyhgA1tnqQS9T3MQPPEsRc.jpg",
          },
          {
            character: "Kuroobi",
            credit_id: "64f133f877d23b00cb862aef",
            order: 553,
            adult: false,
            gender: 2,
            id: 1863259,
            known_for_department: "Acting",
            name: "Jandre le Roux",
            original_name: "Jandre le Roux",
            popularity: 3.906,
            profile_path: "/jZZvq9scQReLz04uCzyaayu959g.jpg",
          },
          {
            character: "Zeff",
            credit_id: "64f31eb577d23b012e8af0a5",
            order: 560,
            adult: false,
            gender: 2,
            id: 51799,
            known_for_department: "Acting",
            name: "Craig Fairbrass",
            original_name: "Craig Fairbrass",
            popularity: 13.016,
            profile_path: "/z5WnSqwkM0Ax0Z47etVNmcew5Pn.jpg",
          },
          {
            character: "Maître d'",
            credit_id: "64f31f451f33190100a4eda0",
            order: 563,
            adult: false,
            gender: 2,
            id: 980004,
            known_for_department: "Acting",
            name: "Royston Stoffels",
            original_name: "Royston Stoffels",
            popularity: 1.571,
            profile_path: "/bOUapLQxeVJpTP2znmbQFhsaOTs.jpg",
          },
          {
            character: "Bartender",
            credit_id: "64f31f6074507d011c1ef164",
            order: 564,
            adult: false,
            gender: 0,
            id: 4248879,
            known_for_department: "Acting",
            name: "Matt von Zweigbergk",
            original_name: "Matt von Zweigbergk",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Chew",
            credit_id: "64f3224be0ca7f012eb37fba",
            order: 571,
            adult: false,
            gender: 0,
            id: 2943486,
            known_for_department: "Acting",
            name: "Len-Barry Simons",
            original_name: "Len-Barry Simons",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Nojiko",
            credit_id: "64f323ba77d23b010d6cdae1",
            order: 583,
            adult: false,
            gender: 1,
            id: 3616915,
            known_for_department: "Acting",
            name: "Chioma Antoinette Umeala",
            original_name: "Chioma Antoinette Umeala",
            popularity: 0.6,
            profile_path: "/9bMIfu5ArEVtvQxX4jAYsDGKk8Y.jpg",
          },
          {
            character: "Bell-mère",
            credit_id: "64f323c777d23b00aec007ef",
            order: 584,
            adult: false,
            gender: 1,
            id: 3479819,
            known_for_department: "Acting",
            name: "Genna Galloway",
            original_name: "Genna Galloway",
            popularity: 1.214,
            profile_path: "/g5Y3lX1JFzya5dJxVSTd6yEGir4.jpg",
          },
          {
            character: "Young Nami",
            credit_id: "64f323df97a4e6011bb097ad",
            order: 585,
            adult: false,
            gender: 1,
            id: 2796434,
            known_for_department: "Acting",
            name: "Lily Fisher",
            original_name: "Lily Fisher",
            popularity: 1.38,
            profile_path: "/a4JWlSmCN3nbD0p0VafHJAHxxOv.jpg",
          },
          {
            character: "Young Nojiko",
            credit_id: "64f323f674507d00adc15f8b",
            order: 586,
            adult: false,
            gender: 0,
            id: 4248902,
            known_for_department: "Acting",
            name: "Kylie Ashfield",
            original_name: "Kylie Ashfield",
            popularity: 0.6,
            profile_path: "/46XUpfJcIW0U2hW8bFuhqGgD6JU.jpg",
          },
          {
            character: "Genzo",
            credit_id: "64f3240674507d00ff8d1dd5",
            order: 587,
            adult: false,
            gender: 2,
            id: 2669277,
            known_for_department: "Acting",
            name: "Grant Ross",
            original_name: "Grant Ross",
            popularity: 0.716,
            profile_path: "/6iC4C3zWwgxJ0jih2ximj12VbZn.jpg",
          },
          {
            character: "Hachi / Angry Fishman",
            credit_id: "64f3245ccaa508014c8cafb4",
            order: 588,
            adult: false,
            gender: 0,
            id: 4248904,
            known_for_department: "Acting",
            name: "Jarid Norman",
            original_name: "Jarid Norman",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Villager",
            credit_id: "64f3248797a4e6011bb09803",
            order: 589,
            adult: false,
            gender: 0,
            id: 2704104,
            known_for_department: "Acting",
            name: "Danielle Bitton",
            original_name: "Danielle Bitton",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Villager #1",
            credit_id: "64f32494caa508010ae7cc84",
            order: 590,
            adult: false,
            gender: 1,
            id: 2193328,
            known_for_department: "Acting",
            name: "Stephanie Hough",
            original_name: "Stephanie Hough",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Villager #2",
            credit_id: "64f324a274507d00c51337d2",
            order: 591,
            adult: false,
            gender: 0,
            id: 2209751,
            known_for_department: "Acting",
            name: "Godfrey Johnson",
            original_name: "Godfrey Johnson",
            popularity: 1.38,
            profile_path: null,
          },
          {
            character: "Toddler Nami",
            credit_id: "64f324b574507d00e2ba74ce",
            order: 592,
            adult: false,
            gender: 0,
            id: 4248910,
            known_for_department: "Acting",
            name: "Sophie Ellenbogen",
            original_name: "Sophie Ellenbogen",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Toddler Nojiko",
            credit_id: "64f324c9e0ca7f00ec87e013",
            order: 593,
            adult: false,
            gender: 0,
            id: 4248913,
            known_for_department: "Acting",
            name: "Elihle Modise",
            original_name: "Elihle Modise",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Belle mère",
            credit_id: "65116015344a8e096d9f1771",
            order: 595,
            adult: false,
            gender: 1,
            id: 3479819,
            known_for_department: "Acting",
            name: "Genna Galloway",
            original_name: "Genna Galloway",
            popularity: 1.214,
            profile_path: "/g5Y3lX1JFzya5dJxVSTd6yEGir4.jpg",
          },
          {
            character: "Usopp",
            credit_id: "6512220426dac1014e232b75",
            order: 596,
            adult: false,
            gender: 2,
            id: 2355316,
            known_for_department: "Acting",
            name: "Jacob Gibson",
            original_name: "Jacob Gibson",
            popularity: 31.665,
            profile_path: "/foaSZvcg70p2gxiJxqtGo3YqWIC.jpg",
          },
        ],
      },
      {
        air_date: "2023-08-31",
        episode_number: 8,
        episode_type: "finale",
        id: 4557395,
        name: "O mais procurado do East Blue",
        overview:
          "A tripulação dos chapéus de palha luta para derrotar Arlong e os homens-peixe de uma vez por todas. Após uma difícil reunião de família, Luffy fica mais perto do seu sonho.",
        production_code: "",
        runtime: 49,
        season_number: 1,
        show_id: 111110,
        still_path: "/nMiFAm30mAkNQS7YGrMEdMCT4NJ.jpg",
        vote_average: 7.839,
        vote_count: 31,
        crew: [
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de23ca59e8a90139d6f800",
            adult: false,
            gender: 2,
            id: 1562489,
            known_for_department: "Writing",
            name: "Matt Owens",
            original_name: "Matt Owens",
            popularity: 2.65,
            profile_path: "/9557f2EgDxHEhnXmXf6Hx9io76S.jpg",
          },
          {
            job: "Writer",
            department: "Writing",
            credit_id: "64de2417d100b614b2ef72c8",
            adult: false,
            gender: 2,
            id: 1225826,
            known_for_department: "Writing",
            name: "Steven Maeda",
            original_name: "Steven Maeda",
            popularity: 2.545,
            profile_path: "/4QwZvyeiOOsIy3jhtLgS5iy7Whw.jpg",
          },
          {
            job: "Director",
            department: "Directing",
            credit_id: "64de24e85ab81a011c2df167",
            adult: false,
            gender: 2,
            id: 1304310,
            known_for_department: "Directing",
            name: "Josef Wladyka",
            original_name: "Josef Wladyka",
            popularity: 5.991,
            profile_path: "/jDwJssEia8lVh5MLvuAI3vDm3jv.jpg",
          },
          {
            job: "Director of Photography",
            department: "Camera",
            credit_id: "64f04bcc4b0c6300abaae2ef",
            adult: false,
            gender: 2,
            id: 1393366,
            known_for_department: "Camera",
            name: "Trevor Michael Brown",
            original_name: "Trevor Michael Brown",
            popularity: 1.614,
            profile_path: null,
          },
          {
            job: "Editor",
            department: "Editing",
            credit_id: "64f04be677d23b015038ee93",
            adult: false,
            gender: 0,
            id: 62702,
            known_for_department: "Editing",
            name: "Tirsa Hackshaw",
            original_name: "Tirsa Hackshaw",
            popularity: 1.4,
            profile_path: null,
          },
        ],
        guest_stars: [
          {
            character: "Captain Nezumi",
            credit_id: "64f0527497a4e600c4869d48",
            order: 501,
            adult: false,
            gender: 2,
            id: 30036,
            known_for_department: "Acting",
            name: "Rory Acton Burnell",
            original_name: "Rory Acton Burnell",
            popularity: 17.413,
            profile_path: "/qxar3nAYjR6Mp5hTcjy1HEckgbP.jpg",
          },
          {
            character: "Yasopp the Great",
            credit_id: "64f052a13a993700e2f78f92",
            order: 502,
            adult: false,
            gender: 0,
            id: 1184468,
            known_for_department: "Acting",
            name: "Stevel Marc",
            original_name: "Stevel Marc",
            popularity: 5.543,
            profile_path: "/n7NzuHjveJqZoEM5HFmblMGKdGp.jpg",
          },
          {
            character: "Lucky Roux",
            credit_id: "64f052c197a4e600fea874f1",
            order: 503,
            adult: false,
            gender: 2,
            id: 2340022,
            known_for_department: "Acting",
            name: "Ntlanhla Morgan Kutu",
            original_name: "Ntlanhla Morgan Kutu",
            popularity: 0.652,
            profile_path: "/c4wO2qJkVE24Wdc1Okz8zEB7gW6.jpg",
          },
          {
            character: "Captain Alvida",
            credit_id: "64f0b3accaa50800e951b80a",
            order: 505,
            adult: false,
            gender: 1,
            id: 3209866,
            known_for_department: "Acting",
            name: "Ilia Isorelýs Paulino",
            original_name: "Ilia Isorelýs Paulino",
            popularity: 3.92,
            profile_path: "/n2TH0b4oCk1Dsc33rrfjdfPgK9e.jpg",
          },
          {
            character: "Makino",
            credit_id: "64f0b40de0ca7f00ec86d76f",
            order: 509,
            adult: false,
            gender: 0,
            id: 4046635,
            known_for_department: "Acting",
            name: "Kathleen Stephens",
            original_name: "Kathleen Stephens",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Bogard",
            credit_id: "64f0b41d3a9937011cbdc02d",
            order: 510,
            adult: false,
            gender: 2,
            id: 1478709,
            known_for_department: "Acting",
            name: "Armand Aucamp",
            original_name: "Armand Aucamp",
            popularity: 3.64,
            profile_path: "/6scoxV13sTnnXFLqVNiHnJU53Yh.jpg",
          },
          {
            character: "Benn Beckman",
            credit_id: "64f0b51877d23b012e89f9d8",
            order: 515,
            adult: false,
            gender: 0,
            id: 1721959,
            known_for_department: "Acting",
            name: "Laudo Liebenberg",
            original_name: "Laudo Liebenberg",
            popularity: 0.84,
            profile_path: null,
          },
          {
            character: "Captain Arlong",
            credit_id: "64f1339597a4e600ac3e8a50",
            order: 548,
            adult: false,
            gender: 2,
            id: 1493226,
            known_for_department: "Acting",
            name: "McKinley Belcher III",
            original_name: "McKinley Belcher III",
            popularity: 21.185,
            profile_path: "/yoglJWyhgA1tnqQS9T3MQPPEsRc.jpg",
          },
          {
            character: "Kaya",
            credit_id: "64f133b177d23b010d6bf263",
            order: 549,
            adult: false,
            gender: 1,
            id: 3456853,
            known_for_department: "Acting",
            name: "Celeste Loots",
            original_name: "Celeste Loots",
            popularity: 0.732,
            profile_path: "/fbUO4PSWS2qzyaVUZkNSzZWe4xt.jpg",
          },
          {
            character: "Kuroobi",
            credit_id: "64f133f877d23b00cb862aef",
            order: 553,
            adult: false,
            gender: 2,
            id: 1863259,
            known_for_department: "Acting",
            name: "Jandre le Roux",
            original_name: "Jandre le Roux",
            popularity: 3.906,
            profile_path: "/jZZvq9scQReLz04uCzyaayu959g.jpg",
          },
          {
            character: "Zeff",
            credit_id: "64f31eb577d23b012e8af0a5",
            order: 560,
            adult: false,
            gender: 2,
            id: 51799,
            known_for_department: "Acting",
            name: "Craig Fairbrass",
            original_name: "Craig Fairbrass",
            popularity: 13.016,
            profile_path: "/z5WnSqwkM0Ax0Z47etVNmcew5Pn.jpg",
          },
          {
            character: "Dracule Mihawk",
            credit_id: "64f31ee1e0ca7f010de4e1f6",
            order: 561,
            adult: false,
            gender: 2,
            id: 1644383,
            known_for_department: "Acting",
            name: "Steven John Ward",
            original_name: "Steven John Ward",
            popularity: 2.318,
            profile_path: "/ssHvaa88N8JdraA76filDejf9jK.jpg",
          },
          {
            character: "Chew",
            credit_id: "64f3224be0ca7f012eb37fba",
            order: 571,
            adult: false,
            gender: 0,
            id: 2943486,
            known_for_department: "Acting",
            name: "Len-Barry Simons",
            original_name: "Len-Barry Simons",
            popularity: 0.6,
            profile_path: null,
          },
          {
            character: "Nojiko",
            credit_id: "64f323ba77d23b010d6cdae1",
            order: 583,
            adult: false,
            gender: 1,
            id: 3616915,
            known_for_department: "Acting",
            name: "Chioma Antoinette Umeala",
            original_name: "Chioma Antoinette Umeala",
            popularity: 0.6,
            profile_path: "/9bMIfu5ArEVtvQxX4jAYsDGKk8Y.jpg",
          },
          {
            character: "Young Nami",
            credit_id: "64f323df97a4e6011bb097ad",
            order: 585,
            adult: false,
            gender: 1,
            id: 2796434,
            known_for_department: "Acting",
            name: "Lily Fisher",
            original_name: "Lily Fisher",
            popularity: 1.38,
            profile_path: "/a4JWlSmCN3nbD0p0VafHJAHxxOv.jpg",
          },
          {
            character: "Genzo",
            credit_id: "64f3240674507d00ff8d1dd5",
            order: 587,
            adult: false,
            gender: 2,
            id: 2669277,
            known_for_department: "Acting",
            name: "Grant Ross",
            original_name: "Grant Ross",
            popularity: 0.716,
            profile_path: "/6iC4C3zWwgxJ0jih2ximj12VbZn.jpg",
          },
          {
            character: "Captain Shanks",
            credit_id: "6504e99f394a87013914afee",
            order: 594,
            adult: false,
            gender: 2,
            id: 1035905,
            known_for_department: "Acting",
            name: "Peter Gadiot",
            original_name: "Peter Gadiot",
            popularity: 22.069,
            profile_path: "/462ODB50nmhpuXdpHz2otQ2rfOy.jpg",
          },
        ],
      },
    ],
    name: "Temporada 1",
    overview: "",
    id: 164867,
    poster_path: "/aesLt9fsKSA6KCgGxA60VVxjtLk.jpg",
    season_number: 1,
    vote_average: 8.1,
  }),
};
