export default {
  TMDBAPI_ITEM_NOT_FOUND_CODE: 34,
  COMBINED_CREDITS_ENDPOINT: '/combined_credits',
  APPEND_TO_RESPONSE_IMAGES_KEY: 'images',
  POPULAR_PERSON_ENDPOINT: '/popular',
  MOVIE_ENDPOINT: '/movie',
  PERSON_ENDPOINT: '/person',
  SEARCH_ENDPOINT: '/search',
  TV_ENDPOINT: '/tv',
  MOVIE_IMAGES_RESOURCE_ENDPOINT: 'images',
  TV_IMAGES_RESOURCE_ENDPOINT: 'images',
  APPEND_TO_TV_SHOW_RESPONSE: 'credits,similar,videos,reviews',
  BASE_URL: 'https://api.themoviedb.org/3',
  INVALID_API_KEY_CODE: 7,
  MEDIA_GENRES_BASE_URL: 'https://api.themoviedb.org/3',
  GENRE_MOVIE_ENDPOINT: '/genre/movie/list',
  GENRE_TV_SHOW_ENDPOINT: '/genre/tv/list',
  APPEND_TO_MOVIE_RESPONSE: 'videos,credits,reviews,similar',
};
