name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, development]

jobs:
  code_check:
    name: Code Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Installing Dependencies
        run: npm install

      - name: Running prettier
        run: npm run prettier:fix

      - name: Running eslint
        run: npm run lint:fix

      - name: Running tests
        run: npm run test

      - name: Building
        run: npm run build
